WIP: popout notes in window
Automattic/simplenote-macos pull request #1141
Opened 2024-04-12 18:22 UTC by charliescheer

### Fix
***(Required)*** Add a concise description of what you fixed.  If this is related to an issue, add a link to it.  If applicable, add screenshots, animations, or videos to help illustrate the fix.

### Test
***(Required)*** List the steps to test the behavior.  For example:
> 1. Go to...
> 2. Tap on...
> 3. See error...

### Review
***(Required)*** Add instructions for reviewers.  For example:
> Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
***(Required)*** Add a concise statement to `RELEASE-NOTES.txt` if the changes should be included in release notes. Include details about updating the notes in this section. For example:
> `RELEASE-NOTES.txt` was updated in d3adb3ef with:
> 
> > Added markdown support

If the changes should not be included in release notes, add a statement to this section. For example:

> These changes do not require release notes.

2024-04-12 18:23 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-04-12 22:50 UTC, roundhill requested changes
This is so cool! I found a bug or at least something I think should be fixed. When you open up a note in the window, make changes, then close it, you won't see the changes to the note in the list view or the editor in the right-pane. We should maybe refresh the notes in the main window after it gets focus again?

2024-04-15 21:16 UTC, roundhill approved these changes
Tested well and code LGTM!

2024-04-15 22:08 UTC, jleandroperez commented on Simplenote/NoteWindowManager.swift
> +    var controllers = Set<NSWindowController>()
```suggestion
    private(set) var controllers = Set<NSWindowController>()
```

2024-04-15 22:08 UTC, jleandroperez commented on Simplenote/SimplenoteAppDelegate+Swift.swift
> +}
Do we still need these?

2024-04-15 22:12 UTC, jleandroperez approved these changes
Working solid on my end. No blockers, feel free to :shipit: Charile!!

2024-04-16 16:57 UTC, merged