Magic Links: Wires new Endpoints
Automattic/simplenote-macos pull request #1188
Opened 2024-07-11 14:27 UTC by jleandroperez

### Fix
In this PR we're wiring the new code-based endpoints.

Ref. #1187

### Test
1. Logout from Simplenote macOS
2. Click on the `Log In` button
3. Enter your email
4. Click on `Instantly Log In with Email`

- [ ] Verify that shortly after you get the Auth Email
- [ ] Verify that clicking on `Log Into Simplenote` button causes the mac app to Log In
- [ ] Verify the Unit Test pass

### Release
> These changes do not require release notes.

2024-07-11 14:28 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-07-11 17:29 UTC, jleandroperez commented on Simplenote/SimplenoteConstants.swift
> +    static let loginCompletionURL           = "https://magic-code-dot-simple-note-hrd.appspot.com/account/complete-login" //googleAppEngineBaseURL.appendingPathComponent("/account/complete-login")
🛑 Important!! This will be reverted before merging!!

2024-07-12 16:13 UTC, charliescheer requested changes
Works as intended, but the unit tests are failing locally and on the CI

2024-07-16 16:20 UTC, jleandroperez commented
Tests fixed, ready for another look. 

Thank you Charlie!!

2024-07-16 21:51 UTC, charliescheer approved these changes
Tests succeed now, thanks!

2024-07-17 13:10 UTC, jleandroperez commented
Thank youuu!!

2024-07-17 13:10 UTC, merged